---
- ansible.builtin.include_tasks: dependencies.yaml

- ansible.builtin.include_tasks: bitwarden.yaml
  when: enable_bitwarden | bool

- name: Initialize dotfiles
  ansible.builtin.command:
    cmd: "chezmoi init {{ github_user }} --data bitwarden_ssh={{ enable_bitwarden }}"
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.config/chezmoi/chezmoi.toml"

- name: Apply dotfiles
  ansible.builtin.command:
    cmd: "chezmoi apply"
  changed_when: true
