hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("systemctl --user start vicinae")
  hl.exec_cmd("systemctl --user start podman.socket")
  hl.exec_cmd("uwsm app -- awww-daemon")
  hl.exec_cmd("uwsm app -- hypridle")
end)
