services:
  fedora-test:
    build:
      context: .
    container_name: fedora-test
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .:/home/docker_user/.dotfiles:ro
