---
- name: Enable COPR repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop:
    - lionheartp/Hyprland
    - leloubil/wl-clip-persist

- name: Install Hyprland ecosystem and display manager
  become: true
  ansible.builtin.dnf:
    name:
      - hyprland
      - sddm
      - hyprland-guiutils
      - xdg-user-dirs
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk

      - hyprqt6engine
      - kvantum
      - hyprcursor

      - hyprpolkitagent
      - gnome-keyring

      - quickshell
      - hypridle
      - hyprpicker

      - thunar
      - alacritty
      - vicinae

      - wl-clipboard
      - wl-clip-persist
      - awww
      - grim
      - slurp
      - swappy
    state: present

- name: Enable SDDM service
  become: true
  ansible.builtin.systemd:
    name: sddm
    enabled: true

- name: Generate XDG user directories
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "~/Downloads"
