---
- name: Set system default target to graphical
  become: true
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Enable COPR repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop:
    - lionheartp/Hyprland
    - leloubil/wl-clip-persist

- name: Install desktop packages
  become: true
  ansible.builtin.dnf:
    name:
      - uwsm
      - hyprland
      - hyprland-guiutils
      - xdg-user-dirs
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk

      - qt5ct
      - qt6ct
      - kvantum
      - hyprcursor
      - jetbrainsmono-nerd-fonts
      - google-noto-color-emoji-fonts
      - bibata-cursor-theme

      - polkit-kde
      - gnome-keyring

      - quickshell
      - hypridle
      - hyprpicker
      - foot
      - yazi
      - wl-clipboard
      - wl-clip-persist
      - awww
      - grim
      - slurp
      - swappy
    state: present

- name: Remove useless desktop packages
  become: true
  ansible.builtin.dnf:
    name:
      - kitty
      - nwg-panel
    state: absent

- name: Setup Vicinae
  block:
    - name: Check if Vicinae is already installed
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/bin/vicinae"
      register: vicinae_binary

    - name: Install Vicinae
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://vicinae.com/install | bash -s -- --prefix "{{ ansible_facts['env']['HOME'] }}/.local"
      args:
        executable: /bin/bash
      register: vicinae_install
      changed_when: "'successfully installed' in vicinae_install.stdout"
      when: not vicinae_binary.stat.exists

- name: Generate XDG user directories
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "~/Downloads"
