---
- name: Enable COPR repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop:
    - lionheartp/Hyprland
    - leloubil/wl-clip-persist

- name: Install desktop packages
  become: true
  ansible.builtin.dnf:
    name:
      - uwsm
      - hyprland
      - hyprland-guiutils
      - xdg-user-dirs
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk

      - hyprqt6engine
      - kvantum
      - nwg-look
      - hyprcursor

      - hyprpolkitagent
      - gnome-keyring

      - quickshell
      - hypridle
      - hyprpicker

      - thunar
      - alacritty
      - vicinae

      - wl-clipboard
      - wl-clip-persist
      - awww
      - grim
      - slurp
      - swappy
    state: present

- name: Remove useless desktop packages
  become: true
  ansible.builtin.dnf:
    name:
      - kitty
      - nwg-panel
    state: absent

- name: Generate XDG user directories
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "~/Downloads"
