---
- name: Ensure Flatpak is installed
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Add Flathub repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps
  become: true
  community.general.flatpak:
    name:
      - it.mijorus.gearlever
      - io.github.flattool.Warehouse
      - org.onlyoffice.desktopeditors
      - com.obsproject.Studio
      - org.localsend.localsend_app
      - io.dbeaver.DBeaverCommunity
      - com.github.tchx84.Flatseal
      - com.usebruno.Bruno
      - com.bitwarden.desktop
      - io.missioncenter.MissionCenter
      - eu.betterbird.Betterbird
    state: present
