---
- name: Install Flatpak
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Setup Flatpak repos
  block:
    - name: Remove default repository
      community.general.flatpak_remote:
        name: fedora
        state: absent

    - name: Add Flathub repository
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps
  become: true
  community.general.flatpak:
    name:
      - org.gnome.Loupe
      - org.gnome.baobab
      - it.mijorus.gearlever
      - io.github.flattool.Warehouse
      - org.onlyoffice.desktopeditors
      - com.obsproject.Studio
      - org.localsend.localsend_app
      - io.dbeaver.DBeaverCommunity
      - com.github.tchx84.Flatseal
      - com.usebruno.Bruno
      - com.bitwarden.desktop
      - io.missioncenter.MissionCenter
      - eu.betterbird.Betterbird
    state: present
