---
- name: Create installation directory for JetBrains Toolbox
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox"
    state: directory
    mode: "0755"

- name: Download and extract JetBrains Toolbox
  ansible.builtin.unarchive:
    src: "https://data.services.jetbrains.com/products/download?code=TBA&platform=linux"
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox"
    remote_src: true
    extra_opts: [--strip-components=1]
