---
- name: Enable COPR repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop:
    - rossetnocpes/herdr

- name: Install system packages
  become: true
  ansible.builtin.dnf:
    name:
      - ffmpeg
      - chezmoi
      - mise
      - tailscale

      - bat
      - eza
      - fzf
      - herdr
      - zoxide
      - gitui
      - lazyssh
      - gh

      - starship
      - fastfetch
      - cava
      - cbonsai

      - "@virtualization"
      - zed
      - vesktop
      - helium-browser-bin
      - mpv
      - nautilus
      - cups
      - system-config-printer
    state: present

- name: Install multimedia group packages
  become: true
  ansible.builtin.dnf:
    name: "@multimedia"
    state: present
    exclude:
      - PackageKit-gstreamer-plugin
      - libheif-freeworld

- name: Enable system services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - cups
    - tailscaled
