---
- name: Install all packages
  become: true
  ansible.builtin.dnf:
    name:
      - uwsm
      - hyprland
      - hyprland-guiutils
      - xdg-user-dirs
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - mate-polkit
      - gnome-keyring

      - qt5ct
      - qt6ct
      - kvantum
      - hyprcursor
      - jetbrainsmono-nerd-fonts
      - google-noto-color-emoji-fonts
      - bibata-cursor-theme

      - quickshell
      - impala
      - bluetui
      - pavucontrol
      - hyprmoncfg
      - hypridle
      - hyprpicker
      - dunst
      - foot
      - wl-clipboard
      - wl-clip-persist
      - awww
      - grim
      - slurp
      - swappy

      - chezmoi
      - mise
      - tailscale
      - bat
      - eza
      - fzf
      - herdr
      - zoxide
      - gitui
      - lazyssh
      - gh
      - starship
      - fastfetch
      - cava
      - cbonsai

      - "@virtualization"
      - zed
      - vesktop
      - helium-browser-bin
      - mpv
      - nautilus
      - cups
      - system-config-printer
    state: present

- name: Remove conflicting and useless packages
  become: true
  ansible.builtin.dnf:
    name:
      - kitty
      - nwg-panel
    state: absent

- name: Setup Vicinae
  block:
    - name: Check if Vicinae is already installed
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/bin/vicinae"
      register: vicinae_binary

    - name: Install Vicinae
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://vicinae.com/install | bash -s -- --prefix "{{ ansible_facts['env']['HOME'] }}/.local"
      args:
        executable: /bin/bash
      register: vicinae_install
      changed_when: "'successfully installed' in vicinae_install.stdout"
      when: not vicinae_binary.stat.exists

- name: Install JetBrains Toolbox
  block:
    - name: Check if JetBrains Toolbox is already installed
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox/jetbrains-toolbox"
      register: toolbox_binary

    - name: Create installation directory for JetBrains Toolbox
      when: not toolbox_binary.stat.exists
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox"
        state: directory
        mode: "0755"

    - name: Download and extract JetBrains Toolbox
      when: not toolbox_binary.stat.exists
      ansible.builtin.unarchive:
        src: "https://data.services.jetbrains.com/products/download?code=TBA&platform=linux"
        dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox"
        remote_src: true
        extra_opts: [--strip-components=2]

- name: Generate XDG user directories
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "~/Downloads"

- name: Enable system services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - cups
    - tailscaled

- name: Set system default target to graphical
  become: true
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
