---
- name: Install all packages
  become: true
  ansible.builtin.dnf:
    name:
      - uwsm
      - hyprland
      - hyprland-guiutils
      - xdg-user-dirs
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - gnome-keyring

      - adw-gtk3-theme
      - qt6ct
      - jetbrainsmono-nerd-fonts
      - google-noto-color-emoji-fonts
      - bibata-cursor-theme

      - noctalia-git
      - bluez
      - hyprmoncfg
      - hyprpicker
      - alacritty
      - wl-clipboard

      - chezmoi
      - mise
      - tailscale
      - bat
      - eza
      - fzf
      - herdr
      - zoxide
      - gitui
      - lazyssh
      - gh
      - starship
      - fastfetch
      - cava
      - cbonsai

      - "@virtualization"
      - zed
      - vesktop
      - helium-browser-bin
      - mpv
      - nautilus
      - cups
      - system-config-printer
    state: present

- name: Remove conflicting and useless packages
  become: true
  ansible.builtin.dnf:
    name:
      - kitty
      - nwg-panel
    state: absent

- name: Install JetBrains Toolbox
  block:
    - name: Check if JetBrains Toolbox is already installed
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox/jetbrains-toolbox"
      register: toolbox_binary

    - name: Create installation directory for JetBrains Toolbox
      when: not toolbox_binary.stat.exists
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox"
        state: directory
        mode: "0755"

    - name: Download and extract JetBrains Toolbox
      when: not toolbox_binary.stat.exists
      ansible.builtin.unarchive:
        src: "https://data.services.jetbrains.com/products/download?code=TBA&platform=linux"
        dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/jetbrains-toolbox"
        remote_src: true
        extra_opts: [--strip-components=2]

- name: Generate XDG user directories
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "~/Downloads"

- name: Enable system services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - cups
    - bluetooth
    - tailscaled

- name: Set system default target to graphical
  become: true
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
