---
- name: Enable COPR repositories
  become: true
  community.general.copr:
    name: atim/lazydocker
    state: enabled

- name: Install Podman and related tools
  become: true
  ansible.builtin.dnf:
    name:
      - podman
      - docker-compose
      - podman-docker
      - podman-tui
      - lazydocker
    state: present

- name: Silence Podman Docker emulation warning
  become: true
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    mode: "0644"
    modification_time: preserve
    access_time: preserve
