---
- name: Install Podman and related tools
  become: true
  ansible.builtin.dnf:
    name:
      - podman
      - docker-compose
      - podman-docker
    state: present

- name: Silence Podman Docker emulation warning
  become: true
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    mode: "0644"
    modification_time: preserve
    access_time: preserve

- name: Enable the Podman socket for all users
  become: true
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    scope: global
