[settings]
minimum_release_age = "1d"

[tools]
node = "24"
bun = "latest"
go = "latest"
rust = "latest"
java = "25"
uv = "latest"

bat = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
starship = "latest"
zoxide = "latest"

lazygit = "latest"
lazydocker = "latest"
lazyssh = "latest"
lazyjournal = "latest"
herdr = "latest"
claude-code = "latest"
