[packages.install]

dnf = [
    "@virtualization",
    "docker-cli",
    "containerd",
    "docker-compose",
    "tailscale",
    "git",
    "fish",
    "@development-tools",
    "code",
    "zed",
    "discord",
    "mise",
    "vicinae",
    "fuse",
    "fuse-libs"
]

flatpak = [
    "it.mijorus.gearlever",
    "io.github.flattool.Warehouse",
    "org.onlyoffice.desktopeditors",
    "org.localsend.localsend_app",
    "io.dbeaver.DBeaverCommunity",
    "com.github.tchx84.Flatseal",
    "com.spotify.Client",
    "app.zen_browser.zen",
    "com.usebruno.Bruno"
]

mise = [
    "node@24",
    "bun",
    "go",
    "rust",
    "java@21",
    "dotnet@10",
    "zig",
    "uv",
    "bat",
    "eza",
    "fzf",
    "jq",
    "ripgrep",
    "zoxide",
    "lazygit",
    "lazyssh",
    "lazydocker",
    "fastfetch",
    "github-cli",
    "starship",
]

brew = []

cask = []

[packages.remove]

dnf = [
    "firefox",
    "libreoffice*",
    "rhythmbox",
    "nheko",
    "thunderbird",
    "podman"
]