[packages.install]

dnf = [
    "@virtualization",
    "moby-engine",
    "docker-compose",
    "tailscale",
    "fish",
    "code",
    "zed",
    "mise",
    "vicinae",
    "helium-browser-bin",
]

flatpak = [
    "it.mijorus.gearlever",
    "io.github.flattool.Warehouse",
    "org.onlyoffice.desktopeditors",
    "org.localsend.localsend_app",
    "io.dbeaver.DBeaverCommunity",
    "dev.vencord.Vesktop",
    "com.github.tchx84.Flatseal",
    "com.spotify.Client",
    "com.usebruno.Bruno",
    "com.bitwarden.desktop",
    "org.gnome.DejaDup",
    "io.missioncenter.MissionCenter",
    "eu.betterbird.Betterbird",
    "io.github.cosmic_utils.Examine",
    "io.github.cosmic_utils.camera",
    "dev.heppen.webapps",
]

mise = [
    "usage",
    "node@24",
    "bun",
    "go@1.26",
    "rust",
    "java@25",
    "dotnet@10",
    "zig",
    "uv",
    "bat",
    "opencode",
    "eza",
    "fzf",
    "jq",
    "ripgrep",
    "zoxide",
    "lazygit",
    "lazyssh",
    "lazydocker",
    "lazyjournal",
    "fastfetch",
    "github-cli",
    "starship",
]

brew = []

cask = []

[packages.remove]

dnf = [
    "firefox",
    "libreoffice*",
    "rhythmbox",
    "nheko",
    "thunderbird",
    "podman",
    "gnome-system-monitor",
    "gnome-calculator",
    "cosmic-store",
]