[theme]
mode = "dark"
source = "community"
community_palette = "Catppuccin Mocha Blue"

[theme.templates]
enable_builtin_templates = true
builtin_ids = ["gtk3", "gtk4", "qt", "alacritty", "hyprland"]
enable_community_templates = true
community_ids = ["bat", "zed", "discord", "hyprtoolkit", "papirus-icons"]
