---
- name: Enable COPR repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop:
    - lionheartp/Hyprland
    - leloubil/wl-clip-persist

- name: Install Hyprland ecosystem and display manager
  become: true
  ansible.builtin.dnf:
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - xfce-polkit
      - gnome-keyring
      - wl-clip-persist
      - ghostty
      - awww
      - ly
    state: present

- name: Enable Ly display manager service
  become: true
  ansible.builtin.systemd:
    name: ly@tty2
    enabled: true
