---
- name: Add Docker official repository
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: "0644"

- name: Enable and start Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add current user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true
