---
- name: Ensure RPM Fusion free and nonfree repositories are installed
  become: true
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: true

- name: Ensure Terra repository is installed
  become: true
  ansible.builtin.dnf:
    name: "https://repos.fyralabs.com/terra{{ ansible_facts['distribution_major_version'] }}/terra-release.noarch.rpm"
    state: present
    disable_gpg_check: true
