---
- name: Ensure RPM Fusion free and nonfree repositories are installed
  become: true
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ major }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ major }}.noarch.rpm"
    state: present
    disable_gpg_check: true
    vars:
      major: "{{ ansible_facts['distribution_major_version'] }}"

- name: Ensure Terra repository is installed
  become: true
  ansible.builtin.shell: |
    dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release
  args:
    creates: /etc/yum.repos.d/terra.repo
