---
- hosts: localhost
  gather_facts: true

  vars_prompt:
    - name: github_user
      prompt: "Enter the GitHub username or organization to fetch the dotfiles from"
      default: "wiizzl"
      private: false

    - name: enable_bitwarden
      prompt: "Do you want to authenticate and retrieve your secrets via Bitwarden?"
      default: "true"
      private: false

  tasks:
    - ansible.builtin.include_role:
        name: fedora
      when: ansible_facts['distribution'] == "Fedora"

    - ansible.builtin.include_role:
        name: macos
      when: ansible_facts['os_family'] == "Darwin"

    - ansible.builtin.include_role:
        name: chezmoi
