[settings]
color_theme = "catppuccin"
minimum_release_age = "0s"

[tools]
usage = "latest"
git = "latest"
bitwarden = "latest"
chezmoi = "latest"
node = "24"
bun = "latest"
go = "latest"
rust = "latest"
java = "25"
zig = "latest"
uv = "latest"
bat = "latest"
eza = "latest"
fzf = "latest"
herdr = "latest"
yazi = "latest"
ripgrep = "latest"
zoxide = "latest"
lazygit = "latest"
lazyssh = "latest"
lazydocker = "latest"
lazyjournal = "latest"
fastfetch = "latest"
github-cli = "latest"
starship = "latest"