name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-fedora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Ansible
        run: pipx install ansible-core

      - name: Start Fedora container with Systemd support
        run: docker compose up -d --build

      - name: Run Ansible
        run: docker exec -u docker_user fedora-test bash -c "cd ~/.dotfiles && ansible-playbook playbook.yaml"

      - name: Clean up
        if: always()
        run: docker compose down

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Ansible
        run: pipx install ansible-core

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.general

      - name: Run Ansible
        run: ansible-playbook playbook.yaml
